### ISSUE TITLE
Causes error when a prop doesn't exists

### ISSUE THREAD

**Issue by prionkor** [vitaly-t/path-value#9]
Consider the example below:

```
import { resolveValue } from "path-value";

const obj = {
  first: {
    secondElse: {}
  }
};

const val = resolveValue(obj, "first.second.value"); 
console.log(val);
```

https://codesandbox.io/s/path-value-6fdpg?file=/src/index.js

### Expected behavior:

Return undefined instead of error or we could create a third argument to be returned as default value.

**Comment by vitaly-t** [comment]
The library replicates that how JavaScript itself behaves. When you try to access a property from a previous property that's `undefined`, you will get the same error in JavaScript.

I understand that you are looking for something synthetic instead, to pass in some defaults for resolution. The first issue with that - what defaults, how many of them, and how they are supposed to affect the ongoing resolution. A property path can have multiple places where it might need to resort to such defaults, not just one. The protocol for this would be not very clear, and quite custom-designed. I tried to keep this library as close to the standard JavaScript as possible.

This library however, is very extensible, and you can easily implement any such defaults logic as you wish, by simply using a lower-level `resolvePath` function.
